/**
 * Code-block script runner for Markdown preview.
 *
 * RuntimeConfig is config-driven: the store holds a list (default shell/node/
 * python); runScript() is generic over any config. Adding a runtime = add a
 * config entry, no logic change.
 *
 * Execution: write code to a temp file, then `/bin/sh -lc '<bin> <tmp>'` via
 * the existing `claude-cli` sidecar (no new Tauri ACL). Temp file avoids the
 * quoting hell of `node -e`/`python -c` for multi-line scripts.
 */

import type { Child } from '@tauri-apps/plugin-shell';

export interface RuntimeConfig {
  /** Stable id, e.g. 'shell' | 'node' | 'python'. */
  id: string;
  /** Human label for settings UI. */
  label: string;
  /** Binary name or absolute path to execute. */
  binaryPath: string;
  /** Markdown fence language aliases that map to this runtime.
   *  e.g. ['bash','sh','shell','zsh']. First entry is the canonical id. */
  languageAliases: string[];
  /** Temp file extension without the dot, e.g. 'sh' | 'js' | 'py'. */
  fileExt: string;
  /** Command to detect the binary path, run via `/bin/sh -lc`. */
  detectCommand: string;
  /** Args to print version, appended to binaryPath. */
  versionArgs: string[];
}

export const DEFAULT_SCRIPT_RUNTIMES: RuntimeConfig[] = [
  {
    id: 'shell',
    label: 'Shell',
    binaryPath: '/bin/sh',
    languageAliases: ['bash', 'sh', 'shell', 'zsh'],
    fileExt: 'sh',
    detectCommand: 'which sh',
    versionArgs: ['--version'],
  },
  {
    id: 'node',
    label: 'Node.js',
    binaryPath: 'node',
    languageAliases: ['js', 'javascript', 'node'],
    fileExt: 'js',
    detectCommand: 'which node',
    versionArgs: ['--version'],
  },
  {
    id: 'python',
    label: 'Python',
    binaryPath: 'python3',
    languageAliases: ['py', 'python', 'python3'],
    fileExt: 'py',
    detectCommand: 'which python3',
    versionArgs: ['--version'],
  },
];

export interface RunHandlers {
  onStdout: (chunk: string) => void;
  onStderr: (chunk: string) => void;
  onClose: (exitCode: number | null) => void;
}

export interface RunningScript {
  child: Child;
  stop: () => Promise<void>;
}

/** Match a markdown fence language string to a runtime config. */
export function mapLanguageToRuntime(
  lang: string | undefined,
  configs: RuntimeConfig[],
): RuntimeConfig | null {
  if (!lang) return null;
  const lower = lang.toLowerCase();
  for (const c of configs) {
    if (c.languageAliases.some((a) => a.toLowerCase() === lower)) return c;
  }
  return null;
}

/** Build sidecar name + args for the runtime + temp file path.
 *  Exported so tests can verify arg shape without spawning. */
export function buildRunArgs(config: RuntimeConfig, tmpPath: string): [sidecar: string, args: string[]] {
  // ponytail: sidecar name 'claude-cli' is already ACL-granted (/bin/sh -lc).
  // Wrap as `-c "<bin> <tmp>"` so a single login shell resolves PATH for
  // nvm/pyenv-installed runtimes.
  const cmd = `${config.binaryPath} ${escapeShellArg(tmpPath)}`;
  return ['claude-cli', ['-l', '-c', cmd]];
}

function escapeShellArg(s: string): string {
  // ponytail: single-quote-escape with '\'' for embedded quotes. Sufficient
  // for file paths that may contain spaces; not a security boundary (the
  // tmp path is generated by us).
  return `'${s.replace(/'/g, `'\\''`)}'`;
}

let tmpCounter = 0;
async function makeTmpPath(fileExt: string): Promise<string> {
  // ponytail: use appDataDir (fs:scope-appdata-recursive) instead of tempDir.
  // tempDir() returns /var/folders/... on macOS, which is outside the fs scope
  // and rejected with "forbidden path". appDataDir is covered by ACL.
  const { appDataDir, join } = await import('@tauri-apps/api/path');
  const { mkdir } = await import('@tauri-apps/plugin-fs');
  const dir = await appDataDir();
  const tmpDir = await join(dir, 'quill-tmp');
  await mkdir(tmpDir, { recursive: true }).catch(() => {});
  const rand = `${Date.now().toString(36)}-${(tmpCounter++).toString(36)}-${Math.random().toString(36).slice(2, 8)}`;
  return join(tmpDir, `quill-run-${rand}.${fileExt}`);
}

/** Write code to a temp file, spawn the runtime, return a controller. */
export async function runScript(
  config: RuntimeConfig,
  code: string,
  handlers: RunHandlers,
): Promise<RunningScript> {
  const { Command } = await import('@tauri-apps/plugin-shell');
  const { writeTextFile, remove } = await import('@tauri-apps/plugin-fs');
  const tmpPath = await makeTmpPath(config.fileExt);
  await writeTextFile(tmpPath, code);

  const [sidecar, args] = buildRunArgs(config, tmpPath);
  const cmd = Command.create(sidecar, args);
  let stdoutBuf = '';
  let stderrBuf = '';
  cmd.stdout.on('data', (line) => {
    stdoutBuf += line + '\n';
    handlers.onStdout(line);
  });
  cmd.stderr.on('data', (line) => {
    stderrBuf += line + '\n';
    handlers.onStderr(line);
  });
  cmd.on('close', (info) => {
    // Best-effort cleanup; ignore errors if file was already removed.
    void remove(tmpPath).catch(() => {});
    handlers.onClose(info.code ?? null);
  });
  const child = await cmd.spawn();
  const stop = async () => {
    try { await child.kill(); } catch {}
  };
  return { child, stop };
}

/** Format the run output as a `> Result:` markdown blockquote. */
export function formatResultBlock(
  stdout: string,
  stderr: string,
  exitCode: number | null,
  stopped: boolean,
): string {
  const lines: string[] = [];
  lines.push('Result:');
  const pushChunk = (text: string, prefix: string) => {
    const trimmed = text.replace(/\n+$/, '');
    if (!trimmed) return;
    for (const ln of trimmed.split('\n')) {
      lines.push(`${prefix}${ln}`);
    }
  };
  pushChunk(stdout, '');
  pushChunk(stderr, '');
  if (stopped) {
    lines.push('[stopped]');
  } else if (exitCode !== null && exitCode !== 0) {
    lines.push(`[exit ${exitCode}]`);
  } else if (exitCode === 0) {
    lines.push('[exit 0]');
  }
  return lines.map((l) => `> ${l}`).join('\n');
}

/**
 * Splice a `> Result:` block into the source content so it follows the code
 * fence that starts at `codeStartLine` (1-based, from rehypeSourceLine).
 *
 * - If a `> Result:` blockquote immediately follows (after ≤1 blank line),
 *   replace its contents with the new block.
 * - Otherwise, insert `\n\n<block>\n` after the closing fence.
 *
 * Invariant: exactly one blank line separates fence → block, and block →
 * following content. Trailing blank lines after the block (if any) are
 * preserved.
 *
 * Returns the new content. If the fence can't be located, returns the
 * original content unchanged (write-back is best-effort).
 */
export function replaceOrAppendResultBlock(
  content: string,
  codeStartLine: number,
  resultBlock: string,
): string {
  const lines = content.split('\n');
  const startIdx = codeStartLine - 1;
  if (startIdx < 0 || startIdx >= lines.length) return content;

  // Find closing fence: a line that starts with ``` (optionally indented)
  // and comes after the opening. Scan from startIdx+1.
  const fenceRe = /^[ \t]*```/;
  let endIdx = -1;
  for (let i = startIdx + 1; i < lines.length; i++) {
    if (fenceRe.test(lines[i])) {
      endIdx = i;
      break;
    }
  }
  if (endIdx === -1) return content; // malformed — bail

  // Locate existing `> Result:` block right after the fence.
  // Allow ≤1 blank line between fence and the blockquote.
  let blkStart = -1;
  for (let i = endIdx + 1; i < lines.length; i++) {
    const t = lines[i].trim();
    if (t === '') continue;
    if (t.startsWith('> Result:')) blkStart = i;
    break;
  }

  let blkEnd = blkStart;
  if (blkStart !== -1) {
    for (let i = blkStart + 1; i < lines.length; i++) {
      if (lines[i].startsWith('>')) {
        blkEnd = i;
      } else if (lines[i].trim() === '') {
        break;
      } else {
        break;
      }
    }
  }

  const before = lines.slice(0, endIdx + 1); // through closing fence
  const after = blkStart !== -1 ? lines.slice(blkEnd + 1) : lines.slice(endIdx + 1);
  // Strip one leading blank line from `after` so we don't double up the
  // fence→block separator. Trailing blanks after the block are preserved
  // as-is (they belong to the following content).
  const afterTrimmed = after.length > 0 && after[0] === '' ? after.slice(1) : after;
  const next = [...before, '', resultBlock, '', ...afterTrimmed];
  return next.join('\n');
}
