/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}', '../../packages/container-plugins/src/**/*.{js,ts,jsx,tsx}'],
  darkMode: ['selector', '[data-theme="dark"]'],
  theme: {
    extend: {
      fontFamily: {
        ui: ['var(--font-ui)', 'sans-serif'],
        mono: ['DM Mono', 'monospace'],
      },
      colors: {
        acc: 'var(--acc)',
        acc2: 'var(--acc2)',
        panel: 'var(--panel)',
        surf: 'var(--surf)',
        surf2: 'var(--surf2)',
        brd: 'var(--brd)',
        brd2: 'var(--brd2)',
        bg: 'var(--bg)',
        hov: 'var(--hov)',
        act: 'var(--act)',
        t1: 'var(--t1)',
        t2: 'var(--t2)',
        t3: 'var(--t3)',
        t4: 'var(--t4)',
        green: 'var(--green)',
        gdim: 'var(--gdim)',
        amber: 'var(--amber)',
        red: 'var(--red)',
        cyan: 'var(--cyan)',
        purple: 'var(--purple)',
        card: 'var(--card)',
        inp: 'var(--inp)',
        accdim: 'var(--accdim)',
        accglow: 'var(--accglow)',
        'ic-md': 'var(--ic-md)',
        'ic-html': 'var(--ic-html)',
        'ic-code': 'var(--ic-code)',
        'ic-img': 'var(--ic-img)',
        'ic-draw': 'var(--ic-draw)',
        'ic-web': 'var(--ic-web)',
        'ic-folder': 'var(--ic-folder)',
        'ic-default': 'var(--ic-default)',
        'ic-ts': 'var(--ic-ts)',
        'ic-js': 'var(--ic-js)',
        'ic-json': 'var(--ic-json)',
        'ic-css': 'var(--ic-css)',
        'ic-yaml': 'var(--ic-yaml)',
        'ic-py': 'var(--ic-py)',
        'ic-sql': 'var(--ic-sql)',
        'ic-pdf': 'var(--ic-pdf)',
      },
    },
  },
  plugins: [],
};
